fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: 'aaa@gmail.com' #"%mailer_user%"
        sender_name: 'aaa@gmail.com' #"%mailer_user%"
